### ISSUE TITLE
Compressing Multiple Operations in one.

### ISSUE THREAD

**Issue by skothari-tibco** [TIBCOSoftware/catalystml#27]
While working on demos, we come across redundancy of operation in spec. For eg 
```
  {
      "operation":"multPairWise",
      "input":{
        "matrix0":"$datatemp['v3*v4']",
        "matrix1":"$datatemp['Visa']"
      },
      "output":"datatemp['v3*v4*Visa']"
    }, 
    {
      "operation":"multPairWise",
      "input":{
        "matrix0":"$datatemp['v2']",
        "matrix1":"$datatemp['v1']"
      },
      "output":"datatemp['v1*v2']"
    } ...
```
We should be able to have just a single operation dealing with multiple data values.
```
  {
      "operation":"multPairWise",
      "input":[
             {
               "matrix0":"$datatemp['v3*v4']",
                "matrix1":"$datatemp['Visa']"
            }, 
          {
               "matrix0":"$datatemp['v2']",
              "matrix1":"$datatemp['v1']"
          }
      ],
      "output":[ "datatemp['v3*v4*Visa'], "datatemp['v1*v2']" ]"
    }
```
The input and output will be mapped one to one accordingly
The pros I can think of, is that the spec would be concise and easy to understand. The con, may be prone to user error in mapping.

Any thoughts @mellistibco @abramvandergeest @fm-tibco ?

**Comment by abramvandergeest** [comment]
okay - unless someone has comments I am going to work with Samip to implement this.

**Comment by abramvandergeest** [comment]
So Samip and I brought this up in our weekly CML meeting.  Frank suggested that instead of making engine level changes that instead create an operation that allows for listed inputs/params.  We will need to update L85 in the spec (how Outputs are defined) to explicitly define how that outputs should work for this operation.

**Comment by abramvandergeest** [comment]
So after long discussion we are shelving this for now to see what users will actually want.
here are several options:
* __applyToInputs__: Applies the name operation to the list of inputs and params.  This way you do not have to list oneHotEncoding (for example) 10 times for each of your catagorical data columns.
    * Input
        * operation/function [string] - operation to apply
        * inputs - [list of objects(defined in named operation)]
        * params - [list of objects(defined in named operation)]
    * Params
        * None
    * OutputType - [any]
    * Output - single string adds output to that variable, list of strings applies output of each input object to the corresponding outputlist item
---------------------------------------------------------
{
   “operation”: “batchOperation”,
   “input”:{
       “operation”:“add”
       “instances”:[
           {
               inputs:{},
               params:{}
           },
           {
               inputs:{}
           }
       ]
   }
   “output” : [“math1", “math2”]
}
 ------------------------------------------------------
{
        "operation": "applyToInputs",
        "params": {
          "params": [
            {
            "sample":2,
            "listOfKeys":["0_0","1_0","2_0","amag_0","0_1","1_1","2_1","amag_1"]
            },
            {
              "sample":3,
              "listOfKeys":["0_0","1_0","2_0","amag_0","0_1","1_1","2_1","amag_1"]
            }
          ],
          "operation" : "math"
        },
        "input": {
          "input": [{
            "inputSample": "23"
          },
            {
              "inputSample": "32"
          }]
        },
        "output" : ["math1", "math2"]
      }

**Comment by abramvandergeest** [comment]
So @fm-tibco, @skothari-tibco and I had a discussion on this topic again.  Since the applyToInputs operation doesn't make a lot of sense I suggested that we go back to the initial idea for multiple inputs/params which is to allow an operation to have either an object or an array for the inputs and params components.  I will now include this into the specification.
Below are three examples of how

  {
      "operation":"multPairWise",
      "input":[
             {
               "matrix0":"$datatemp['v3*v4']",
                "matrix1":"$datatemp['Visa']"
            }, 
            {
               "matrix0":"$datatemp['v2']",
              "matrix1":"$datatemp['v1']"
            }
      ],
     "params":[
             {}, 
             {
               "param1":6,
               "param2":5
             }
      ],
      "output":[ "datatemp['v3*v4*Visa']", "datatemp['v1*v2']" ]
}

  {
      "operation":"multPairWise",
      "input":[
             {
               "matrix0":"$datatemp['v3*v4']",
                "matrix1":"$datatemp['Visa']"
            }, 
          {
               "matrix0":"$datatemp['v2']",
              "matrix1":"$datatemp['v1']"
          }
      ],
     "params":
          {
               "param1":6,
              "param2":5
          }
    ,
      "output":[ "datatemp['v3*v4*Visa']", "datatemp['v1*v2']" ]
}

  {
      "operation":"multPairWise",
      "input":
            {
               "matrix0":"$datatemp['v2']",
              "matrix1":"$datatemp['v1']"
            },
     "params":[
             {}, 
             {
               "param1":6,
               "param2":5
             }
      ],
      "output":[ "datatemp['v3*v4*Visa']", "datatemp['v1*v2']" ]
  }

**Comment by abramvandergeest** [comment]
addressed in PR https://github.com/TIBCOSoftware/catalystml/pull/41
