### ISSUE TITLE
Do we need a "toFile" Operation that write data to file?

### ISSUE THREAD

**Issue by abramvandergeest** [TIBCOSoftware/catalystml#36]
Do you think there is a need to "benchmark" a cml structure partway through?

**Comment by mellistibco** [comment]
I don't think this is really required imo... I think we can look at more debugging type capabilities from an implementation perspective, but don't really think the spec needs to define an operation to output the results to file.

**Comment by abramvandergeest** [comment]
@mellistibco  - This seems reasonable to me.  I also like your phone suggestion that we have an operation that writes a variable to log.  So that it can be read externally if needed.  That way you don't have to worry if a toFile op is left in for production and it breaks because of file permission issues.  So I can add a toLog operation to the spec.

**Comment by abramvandergeest** [comment]
Done
